---
- name: set graphical runlevel
  command: systemctl set-default graphical.target
  listen: server with gui installed

- name: define eclipse desktop
  template:
    src: eclipse-ide.desktop.j2
    dest: /usr/share/applications/eclipse-ide.desktop
    owner: root
    group: root
    mode: '0644'
  listen: eclipse tar bundle installed

- name: delete eclipse bundle
  file: path=/home/vagrant/eclipse.tar.gz state=absent
  listen: eclipse bundle staged

- name: create eclipse symbolic link
  file:
    src: /opt/eclipse/eclipse
    dest: /usr/local/bin/eclipse
    owner: root
    group: root
    state: link
  listen: eclipse bundle installed
