---
- debug:
    msg: vbox_guest_additions_url is defined as {{ vbox_guest_additions_url }}

- name: stage vbox guest additions iso
  get_url:
    url: "{{ vbox_guest_additions_url }}"
    dest: /home/vagrant/VBoxGuestAdditions.iso
    owner: vagrant
    group: vagrant
    mode: 0644
  notify: "vbox guest additions iso staged"

- name: mount vbox guest additions iso
  mount:
    name: /media/cdrom
    src: /home/vagrant/VBoxGuestAdditions.iso
    fstype: iso9660
    opts: noauto
    state: mounted
  notify: "vbox guest additions iso mounted"

- name: install vbox guest additions
  command: /media/cdrom/VBoxLinuxAdditions.run
  notify: "vbox guest additions installed"
