apiVersion: v1
kind: Pod
metadata:
  name: dns-utils
spec:
  dnsPolicy: ClusterFirst
  # hostAliases:
  # - ip: "192.168.133.100"
  #   hostnames: [ "k8s-master.local", "k8s-master" ]
  # - ip: "192.168.133.101"
  #   hostnames: [ ]"k8s-node01.local", "k8s-node01" ]
  # - ip: "192.168.133.102"
  #   hostnames: [ "k8s-node02.local", "k8s-node02" ]
  restartPolicy: Never
  containers:
  - image: tutum/dnsutils:latest
    # command: ["nslookup", "$(NODE_NAME)"]
    command: ["sleep", "infinity"]
    name: node-name
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
