---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: hello
        image: jefferysedwards/hello:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: JAVA_OPTS
          value: -Dhttp.proxyHost=$(NODE_NAME) -Dhttp.proxyPort=4140
        - name: WORLD_URI
          value: http://world-service.default
        ports:
        - name: service
          containerPort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 8888
