---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      dnsPolicy: ClusterFirst
      hostAliases:
      - ip: "192.168.33.200"
        hostnames: [ "k8s-master.local", "k8s-master" ]
      - ip: "192.168.33.201"
        hostnames: [ "k8s-node01.local", "k8s-node01" ]
      - ip: "192.168.33.202"
        hostnames: [ "k8s-node02.local", "k8s-node02" ]
      restartPolicy: Always
      containers:
      - name: hello
        image: jefferysedwards/hello:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JAVA_OPTS
          value: -Dhttp.proxyHost=$(NODE_NAME) -Dhttp.proxyPort=4140
        - name: WORLD_URI
          value: http://world-service.default
        ports:
        - name: service
          containerPort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
spec:
  ports:
  - port: 80
    targetPort: service
  selector:
    app: hello
  type: ClusterIP
