---
apiVersion: v1
kind: ConfigMap
metadata:
  name: l5d-config
  namespace: default

data:
  config.yaml: |-
    admin:
      ip: 0.0.0.0
      port: 9990

    namers:
    # The "basic" k8s namer.  We reference this in the incoming router's dtab
    - kind: io.l5d.k8s

    # This namer has the daemonset transformer "built-in"
    - kind: io.l5d.k8s
      prefix: /io.l5d.k8s.ds
      transformers:
      - kind: io.l5d.k8s.daemonset
        namespace: default
        port: incoming
        service: l5d

    telemetry:
    - kind: io.l5d.prometheus
    - kind: io.l5d.recentRequests
      sampleRate: 0.25

    usage:
      enabled: false
      orgId: service-mesh

    routers:
    - label: outgoing
      protocol: http
      dtab: |
        /ph        => /$/io.buoyant.rinet ;             # Lookup the name in DNS
        /srv       => /ph/80 ;                          # Use port 80 if unspecified
        /srv       => /$/io.buoyant.porthostPfx/ph ;    # Attempt to extract the port from the hostname
        /srv       => /#/io.l5d.k8s.ds/default/http ;   # Lookup the name in Kubernetes, use the linkerd daemonset pod
        /svc       => /srv ;
      servers:
      - port: 4140
        ip: 0.0.0.0
      service:
        responseClassifier:
          kind: io.l5d.http.retryableRead5XX

    - label: incoming
      protocol: http
      dtab: |
        /srv        => /#/io.l5d.k8s/default/http;
        /host       => /srv;
        /svc        => /host;
      interpreter:
        kind: default
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4141
        ip: 0.0.0.0

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: l5d
  name: l5d
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: l5d
    spec:
      volumes:
      - name: l5d-config
        configMap:
          name: "l5d-config"
      containers:
      - name: l5d
        image: buoyantio/linkerd:1.3.5
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        args: [ "/io.buoyant/linkerd/config/config.yaml" ]
        ports:
        - name: outgoing
          containerPort: 4140
          hostPort: 4140
        - name: incoming
          containerPort: 4141
        - name: admin
          containerPort: 9990
        volumeMounts:
        - name: "l5d-config"
          mountPath: "/io.buoyant/linkerd/config"
          readOnly: true

      - name: kubectl
        image: buoyantio/kubectl:v1.8.5
        args: [ "proxy",  "-p",  "8001" ]

---
apiVersion: v1
kind: Service
metadata:
  name: l5d
  namespace: default
spec:
  selector:
    app: l5d
  type: NodePort
  ports:
  - name: outgoing
    port: 4140
  - name: incoming
    port: 4141
  - name: admin
    port: 9990
