---
- name:  Worker Playbook
  hosts: all
  gather_facts: false
  remote_user: vagrant
  become: yes
  become_method: sudo
  vars:
    kubeadm_join: "{{ lookup('file', '/vagrant/kubeadm_join') }}"
  roles:
    - worker
    - common
