---
- name: install packages
  yum: name={{ packages }} state=latest update_cache=yes
  vars:
    packages:
    - dkms
    - kernel-devel
    - kernel-headers
    - net-tools

- name: install development tools group
  yum: name="@development tools" state=latest update_cache=yes

- name: install docker packages
  yum: name={{ packages }} state=latest update_cache=yes enablerepo="docker-ce"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: docker installed

- name: install kubernetes packages
  yum: name={{ packages }} state=latest update_cache=yes enablerepo="kubernetes"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
  notify: kubernetes installed
