---
- name: install packages
  yum: name={{ packages }} state=latest update_cache=yes
  vars:
    packages:
    - dkms
    - kernel-devel
    - kernel-headers
    - net-tools

- name: install development tools group
  yum: name="@development tools" state=latest update_cache=yes

- name: install docker packages
  yum: name={{ packages }} state=latest update_cache=yes enablerepo="docker-ce"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: docker installed

- name: install kubernetes packages
  yum: name={{ packages }} state=latest update_cache=yes enablerepo="kubernetes"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
  notify: kubernetes installed

- debug:
    msg: gradle_version is defined as {{ gradle_version }}

- debug:
    msg: gradle_download_url is defined as {{ gradle_download_url }}

- name: stage gradle bundle
  get_url:
    url: "{{ gradle_download_url }}"
    dest: /home/vagrant/gradle.zip
    owner: vagrant
    group: vagrant
    mode: 0644
  notify: gradle bundle staged

- name: install gradle bundle
  unarchive:
    src: /home/vagrant/gradle.zip
    remote_src: yes
    dest: /opt
    owner: root
    group: root
  notify: gradle bundle installed
