---
- name: set selinux to disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'

- name: disable swap
  command: swapoff -a

- name: remove reference to swap in /etc/fstab
  lineinfile: dest=/etc/fstab regexp='^.*swap.*$' state=absent

- name: uninstall wpa_supplicant package
  yum: name=wpa_supplicant state=absent

- name: uninstall vbox guest additions
  shell: /opt/VBoxGuestAdditions*/uninstall.sh
  args:
    removes: /usr/share/VBoxGuestAdditions

- name: update /etc/sysctl.d/default.conf
  blockinfile:
    create: yes
    dest: /etc/sysctl.d/default.conf
    owner: root
    group: root
    mode: 0644
    block: |
      # required by k8s
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      # disable ipv6
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
      net.ipv6.conf.eth0.disable_ipv6 = 1
      net.ipv6.conf.eth1.disable_ipv6 = 1

- name: sysctl --system
  command: sysctl --system

- name: define docker repo
  template:
    src: docker-ce.repo.j2
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: '0644'

- name: define kubernetes repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '0644'

- name: update kernel and install epel-release package
  yum: name={{ packages }} state=latest update_cache=yes
  vars:
    packages:
    - kernel
    - epel-release

- name: install packages
  yum: name={{ packages }} state=latest update_cache=yes
  vars:
    packages:
    - bzip2
    - dkms
    - firefox
    - gcc
    - kernel-devel
    - kernel-headers
    - make
    - net-tools
    - perl

- name: install x11 packages
  yum: name="@x11" state=latest update_cache=yes
  notify: x11 installed

- name: install docker dependent packages
  yum: name={{ packages }} state=latest update_cache=yes
  vars:
    packages:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: install docker packages
  yum: name={{ packages }} state=latest update_cache=yes enablerepo="docker-ce"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: docker installed

- name: install kubernetes packages
  yum: name={{ packages }} state=latest update_cache=yes enablerepo="kubernetes"
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl
  notify: kubernetes installed
