##
## Create the Geo Server image.
##
FROM jedwards/tomcat9

ARG \
  GEOSERVER_HOME="/var/geoserver" \
  GEOSERVER_VERSION="2.20.4" \
  LIBJPEG_TURBO_VERSION="2.1.3"

ENV \
  GEOSERVER_VERSION="${GEOSERVER_VERSION}" \
  LIBJPEG_TURBO_VERSION="${LIBJPEG_TURBO_VERSION}" \
  \
  GEOSERVER_HOME="${GEOSERVER_HOME}" \
  GEOSERVER_DATA_DIR="${GEOSERVER_HOME}/data" \
  GEOSERVER_LOG_DIR="${GEOSERVER_HOME}/logs" \
  GEOSERVER_LOG_LOCATION="${GEOSERVER_LOG_DIR}/geoserver.log" \
  GEOWEBCACHE_CONFIG_DIR="${GEOSERVER_DATA_DIR}/gwc/config" \
  GEOWEBCACHE_CACHE_DIR="${GEOSERVER_HOME}/gwc/cache" \
  NETCDF_DATA_DIR="${GEOSERVER_HOME}/netcdf/data"

USER root

COPY scripts /scripts
RUN \
  /scripts/setup.sh; \
  rm -rf /scripts

RUN \
  set -eux; \
  \
  dnf -y install \
    gdal \
    gdal-devel \
    gdal-java; \
  \
  # housekeeping
  chown -R tomcat. \
    ${CATALINA_HOME} \
    ${GEOSERVER_HOME}; \
  dnf -y autoremove; \
  dnf clean all

USER tomcat
VOLUME [ "${GEOSERVER_HOME}" ]