# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = false if Vagrant.has_plugin?("vagrant-hostmanager")
  config.vbguest.auto_update = false if Vagrant.has_plugin?("vagrant-vbguest")

  config.vm.box = "k8s/centos"
  config.vm.box_check_update = false
  config.vm.box_download_insecure = true

  # ssh settings
  config.ssh.private_key_path = ["~/.ssh/id_rsa"]
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--name", "scratch"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--cpuexecutioncap", "100"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

end
