server:
  port: ${consumer.server.port:0}
spring:
  application:
    name: example-consumer
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
       defaultZone: ${eureka.server.uri}
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
