version: "3.7"
services:

  elasticsearch:
    container_name: demo-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data:rw                 # Persistence data

  logstash:
    container_name: demo-logstash
    image: docker.elastic.co/logstash/logstash:7.3.2
    ports:
      - "25826:25826"
      - "5044:5044"
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro  # Pipeline configuration
    restart: on-failure
    depends_on:
      - elasticsearch

  kibana:
    container_name: demo-kibana
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch

  filebeat:
    container_name: demo-filebeat
    image: docker.elastic.co/beats/filebeat:7.3.2
    volumes:
      - filebeat-volume:/usr/share/filebeat/data:rw                           # Persistence data
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro             # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro              # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                          # Additional information about containers
    user: root                                                                # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash

  demo-service:
    container_name: demo-service
    image: net/edwardsonthe/docker-service:latest
    ports:
      - "8000:8000"
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

volumes:
  elasticsearch-volume:
    driver: local
  filebeat-volume:
    driver: local
