FROM docker.elastic.co/logstash/logstash:7.3.2
MAINTAINER Jeff Edwards <jeff@edwardsonthe.net>

VOLUME 	/tmp
WORKDIR	/app

USER root

ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib 	./lib
COPY ${DEPENDENCY}/BOOT-INF/classes .
COPY ${DEPENDENCY}/META-INF 		./META-INF

RUN mkdir logs

CMD ["java", "-cp",".:./lib/*", "-Dspring.profiles.active=docker", "net.edwardsonthe.Application"]
