apiVersion: v1
kind: Pod
metadata:
  name: dns-utils
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
  - image: tutum/dnsutils:latest
    # command: ["nslookup", "$(NODE_NAME)"]
    command: ["sleep", "infinity"]
    name: node-name
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
