---
- include: repos.yml

- name: set selinux to disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'

- name: disable swap
  command: swapoff -a

- name: remove reference to swap in /etc/fstab
  lineinfile: dest=/etc/fstab regexp='^.*swap.*$' state=absent

- name: uninstall wpa_supplicant package
  yum: name=wpa_supplicant state=absent

- name: update /etc/sysctl.d/default.conf
  blockinfile:
    create: yes
    dest: /etc/sysctl.d/default.conf
    owner: root
    group: root
    mode: 0644
    block: |
      # required by k8s
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      # disable ipv6
      net.ipv6.conf.all.disable_ipv6 = 1
      net.ipv6.conf.default.disable_ipv6 = 1
      net.ipv6.conf.lo.disable_ipv6 = 1
      net.ipv6.conf.eth0.disable_ipv6 = 1
      net.ipv6.conf.eth1.disable_ipv6 = 1

- name: sysctl --system
  command: sysctl --system

- name: increase yum timeout
  lineinfile: dest=/etc/yum.conf regexp='^timeout=' line='timeout=900'

- name: install the CA root certificate bundle
  yum: name='ca-certificates' state=latest update_cache=yes

- name: upgrade all packages
  yum: name='*' state=latest update_cache=yes

- name: install epel-release package
  yum: name=epel-release state=latest update_cache=yes
